services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "photos"
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - photos-db:/var/lib/postgresql/data

  photos:
    container_name: photos
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      EXAMPLE_ENV: "hoi"
    depends_on:
      - postgres
    ports:
      - "9475:9475"
    networks:
      - backend
    volumes:
      - ${PHOTOS_DIR}:/app/data/photos
      - ${THUMBNAILS_DIR}:/app/data/thumbnails

volumes:
  photos-db:

networks:
  backend:
    driver: bridge