services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "photos"
    networks:
      - backend
    volumes:
      - photos-db:/var/lib/postgresql/data

  photos:
    container_name: photos
    build:
      context: ruurd-photos-backend
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - 9475:9475
    volumes:
      - ${PHOTOS_DIR}:/app/data/photos
      - ${THUMBNAILS_DIR}:/app/data/thumbnails

volumes:
  photos-db:

networks:
  backend:
    driver: bridge