[tool.poetry]
name = "Ruurd Photos"
version = "2.0.0"
description = ""
authors = ["Ruurd Bijlsma <ruurd@bijlsma.dev>"]
license = "AGPL"
readme = "README.md"
packages = [{ include = "*", from = "photos" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.3"
pydantic = "^2.9.2"
uvicorn = "^0.32.0"
pydantic-settings = "^2.6.0"
alembic = "^1.13.3"
sqlalchemy = { extras = ["asyncio"], version = "^2.0.36" }
asyncpg = "^0.30.0"
async-lru = "^2.0.4"
pyexiftool = "^0.5.6"
pillow = "^11.0.0"
tqdm = "^4.66.5"
reverse-geocode = "^1.6.5"
parsed-ffmpeg = "^0.2.3"
pytz = "^2024.2"
timezonefinder = "^6.5.4"
watchdog = "6.0.0"
pyjwt = "^2.9.0"
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
python-multipart = "0.0.17"
pillow-avif-plugin = "^1.4.6"
meteostat = "^1.6.8"
transformers = "^4.46.2"
torch = [
    { version = "^2.5.1+cpu", source = "pytorch_cpu", markers = "platform_machine=='x86_64'", platform = "linux" },
    { version = "^2.5.1", source = "pytorch_gpu", markers = "platform_machine!='x86_64'", platform = "linux" },
    { version = "^2.5.1", source = "pytorch_gpu", platform = "darwin" },
    { version = "^2.5.1", source = "pytorch_gpu", platform = "Windows" },
]
torchvision = [
    { version = "^0.20.1+cpu", source = "pytorch_cpu", markers = "platform_machine=='x86_64'", platform = "linux" },
    { version = "^0.20.1", source = "pytorch_gpu", markers = "platform_machine!='x86_64'", platform = "linux" },
    { version = "^0.20.1", source = "pytorch_gpu", platform = "darwin" },
    { version = "^0.20.1", source = "pytorch_gpu", platform = "Windows" },
]
pytesseract = "^0.3.13"
bitsandbytes = "^0.44.1"
accelerate = "^1.1.1"
sentencepiece = "^0.2.0"
opencv-python = "^4.10.0.84"
insightface = "^0.7.3"
onnxruntime = "^1.20.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"
mypy = "^1.13.0"
types-tqdm = "^4.66.0.20240417"
types-pytz = "^2024.2.0.20241003"
ruff = "^0.7.2"
types-passlib = "^1.7.7.20240819"
pytest = "^8.3.3"


[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[[tool.poetry.source]]
name = "pytorch_gpu"
url = "https://download.pytorch.org/whl/cu124"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
