[tool.poetry]
name = "Ruurd Photos"
version = "2.0.0"
description = ""
authors = ["Ruurd Bijlsma <ruurd@bijlsma.dev>"]
license = "AGPL"
readme = "README.md"
packages = [{ include = "*", from = "photos" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.3"
pydantic = "^2.9.2"
uvicorn = "^0.32.0"
pydantic-settings = "^2.6.0"
alembic = "^1.13.3"
sqlalchemy = { extras = ["asyncio"], version = "^2.0.36" }
asyncpg = "^0.30.0"
async-lru = "^2.0.4"
pyexiftool = "^0.5.6"
pillow = "^11.0.0"
tqdm = "^4.66.5"
reverse-geocode = "^1.6.5"
parsed-ffmpeg = "^0.2.3"
pytz = "^2024.2"
timezonefinder = "^6.5.4"
watchdog = "^5.0.3"
pyjwt = "^2.9.0"
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
python-multipart = "^0.0.16"
pillow-avif-plugin = "^1.4.6"
meteostat = "^1.6.8"
torch = { version = "^2.5.1+cpu", source = "pytorch_cpu", platform = "linux" }
torchvision = { version = "^0.20.1+cpu", source = "pytorch_cpu", platform = "linux" }


[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"
mypy = "^1.13.0"
types-tqdm = "^4.66.0.20240417"
types-pytz = "^2024.2.0.20241003"
ruff = "^0.7.2"


[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
