[tool.poetry]
name = "Ruurd Photos"
version = "2.0.0"
description = ""
authors = ["Ruurd Bijlsma <ruurd@bijlsma.dev>"]
license = "AGPL"
readme = "../README.md"
packages = [{ include = "*", from = "photos" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = { extras = ["all"], version = "^0.115.0" }
sqlalchemy = { extras = ["mypy"], version = "^2.0.35" }
uvicorn = "^0.31.0"
httpx = "^0.27.2"
pillow = "^10.4.0"
psycopg2-binary = "^2.9.9"
watchdog = "^5.0.3"
tqdm = "^4.66.5"
pre-commit = "^3.8.0"
types-tqdm = "^4.66.0.20240417"
pydantic-settings = "^2.5.2"
alembic = "^1.13.3"
pydantic = { extras = ["dotenv"], version = "^2.9.2" }
reverse-geocode = "^1.6.5"
timezonefinder = "^6.5.3"
pytz = "^2024.2"
types-pytz = "^2024.2.0.20241003"
pyjwt = "^2.9.0"
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
types-passlib = "^1.7.7.20240819"
pyexiftool = "^0.5.6"
parsed-ffmpeg = {extras = ["tqdm"], version = "^0.2.1"}
transformers = "^4.45.2"
torch = {version = "^2.5.0+cu118", source = "pytorch-gpu"}
torchvision = {version = "^0.20.0+cu118", source = "pytorch-gpu"}
torchaudio = {version = "^2.5.0+cu118", source = "pytorch-gpu"}
llama-stack = "^0.0.43"
diffusers = "^0.31.0"
accelerate = "^1.0.1"
safetensors = "^0.4.5"
timm = "^1.0.11"
sentencepiece = "^0.2.0"
peft = "^0.13.2"
llama-cpp-python = "^0.3.1"


[tool.poetry.group.dev.dependencies]
mypy = "^1.11.2"


[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"